title: Index
logo: 'https://raw.githubusercontent.com/bitlecture/bitlecture.github.io/master/assets/img/logo.png'
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
